import { readFileSync } from "node:fs";
import path from "node:path";

export const dynamic = "force-static";

/**
 * Serves public/llms.txt (generated by scripts/aio-llms.mjs).
 * The URL index from the previous route is preserved inside that file,
 * followed by services, prices, technical points and 10 questions.
 */
export function GET() {
  const body = readFileSync(path.join(process.cwd(), "public", "llms.txt"), "utf8");
  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
